# Generated by Django 5.2.9 on 2026-05-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivy_chat', '0002_alter_chatmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatday',
            name='title',
            field=models.CharField(blank=True, default='', help_text='AI-generated summary title for this day', max_length=120),
        ),
    ]
